# format version
version: '3'

# docker images
services:
  db:
    image: postgres
  web:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - 5000:80
    depends_on:
      - db
