# format version
version: '3'

# docker images
services:
  # db:
  #   image: postgres
  api:
    build: api
    command: python app.py
    # match Dockerfile to enable auto-reload
    volumes:
      - ./api:/api
    ports:
      - 5000:80
    # depends_on:
    #   - db
  client:
    build: client
    command: python app.py
    volumes:
      - ./client:/app
    ports:
      - 5001:8080
    depends_on:
      - api
